name: test-all
on:
    push:
        branches:
            - feature/*
            - develop
            - main
        paths:
            - "packages/**"
            - ".github/workflows/**"
            - "package.json"
            - "pnpm-lock.yaml"
            - "!**.md"
    pull_request:
        branches:
            - develop
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ">=17.5.0"
                  cache: "pnpm"
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.10.0
            - run: pnpm i
            - run: pnpm test
            - run: pnpm tool:imports
